all:
	g++ src/main.cpp src/code.cpp src/parser.cpp -o bin/executable
compile:
	g++ src/main.cpp src/code.cpp src/parser.cpp -o bin/executable
clean:
	rm -f tests/FunctionCalls/NestedCall/*.asm	
	rm -f tests/FunctionCalls/StaticsTest/*.asm
	rm -f tests/FunctionCalls/SimpleFunction/*.asm
	rm -f tests/FunctionCalls/FibonacciElement/*.asm
